<?php

/**
 * Base class that represents a row from the 'picture' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0-dev on:
 *
 * Wed Mar 31 16:35:31 2010
 *
 * @package    lib.model.om
 */
abstract class BasePicture extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        PicturePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the content field.
	 * @var        string
	 */
	protected $content;

	/**
	 * The value for the userid field.
	 * @var        int
	 */
	protected $userid;

	/**
	 * The value for the owner field.
	 * @var        int
	 */
	protected $owner;

	/**
	 * The value for the stat field.
	 * @var        int
	 */
	protected $stat;

	/**
	 * The value for the cost field.
	 * @var        double
	 */
	protected $cost;

	/**
	 * The value for the name field.
	 * @var        string
	 */
	protected $name;

	/**
	 * The value for the modeid field.
	 * @var        int
	 */
	protected $modeid;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the rank field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $rank;

	/**
	 * The value for the privte field.
	 * @var        boolean
	 */
	protected $privte;

	/**
	 * The value for the not_for_sale field.
	 * @var        boolean
	 */
	protected $not_for_sale;

	/**
	 * The value for the hidden field.
	 * @var        boolean
	 */
	protected $hidden;

	/**
	 * @var        Usr
	 */
	protected $aUsrRelatedByUserid;

	/**
	 * @var        Usr
	 */
	protected $aUsrRelatedByOwner;

	/**
	 * @var        Mode
	 */
	protected $aMode;

	/**
	 * @var        array PictureComment[] Collection to store aggregation of PictureComment objects.
	 */
	protected $collPictureComments;

	/**
	 * @var        Criteria The criteria used to select the current contents of collPictureComments.
	 */
	private $lastPictureCommentCriteria = null;

	/**
	 * @var        array Test[] Collection to store aggregation of Test objects.
	 */
	protected $collTests;

	/**
	 * @var        Criteria The criteria used to select the current contents of collTests.
	 */
	private $lastTestCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'PicturePeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->rank = 0;
	}

	/**
	 * Initializes internal state of BasePicture object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [content] column value.
	 * 
	 * @return     string
	 */
	public function getContent()
	{
		return $this->content;
	}

	/**
	 * Get the [userid] column value.
	 * 
	 * @return     int
	 */
	public function getUserid()
	{
		return $this->userid;
	}

	/**
	 * Get the [owner] column value.
	 * 
	 * @return     int
	 */
	public function getOwner()
	{
		return $this->owner;
	}

	/**
	 * Get the [stat] column value.
	 * 
	 * @return     int
	 */
	public function getStat()
	{
		return $this->stat;
	}

	/**
	 * Get the [cost] column value.
	 * 
	 * @return     double
	 */
	public function getCost()
	{
		return $this->cost;
	}

	/**
	 * Get the [name] column value.
	 * 
	 * @return     string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Get the [modeid] column value.
	 * 
	 * @return     int
	 */
	public function getModeid()
	{
		return $this->modeid;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->created_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->updated_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [rank] column value.
	 * 
	 * @return     int
	 */
	public function getRank()
	{
		return $this->rank;
	}

	/**
	 * Get the [privte] column value.
	 * 
	 * @return     boolean
	 */
	public function getPrivte()
	{
		return $this->privte;
	}

	/**
	 * Get the [not_for_sale] column value.
	 * 
	 * @return     boolean
	 */
	public function getNotForSale()
	{
		return $this->not_for_sale;
	}

	/**
	 * Get the [hidden] column value.
	 * 
	 * @return     boolean
	 */
	public function getHidden()
	{
		return $this->hidden;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Picture The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = PicturePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [content] column.
	 * 
	 * @param      string $v new value
	 * @return     Picture The current object (for fluent API support)
	 */
	public function setContent($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->content !== $v) {
			$this->content = $v;
			$this->modifiedColumns[] = PicturePeer::CONTENT;
		}

		return $this;
	} // setContent()

	/**
	 * Set the value of [userid] column.
	 * 
	 * @param      int $v new value
	 * @return     Picture The current object (for fluent API support)
	 */
	public function setUserid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->userid !== $v) {
			$this->userid = $v;
			$this->modifiedColumns[] = PicturePeer::USERID;
		}

		if ($this->aUsrRelatedByUserid !== null && $this->aUsrRelatedByUserid->getId() !== $v) {
			$this->aUsrRelatedByUserid = null;
		}

		return $this;
	} // setUserid()

	/**
	 * Set the value of [owner] column.
	 * 
	 * @param      int $v new value
	 * @return     Picture The current object (for fluent API support)
	 */
	public function setOwner($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->owner !== $v) {
			$this->owner = $v;
			$this->modifiedColumns[] = PicturePeer::OWNER;
		}

		if ($this->aUsrRelatedByOwner !== null && $this->aUsrRelatedByOwner->getId() !== $v) {
			$this->aUsrRelatedByOwner = null;
		}

		return $this;
	} // setOwner()

	/**
	 * Set the value of [stat] column.
	 * 
	 * @param      int $v new value
	 * @return     Picture The current object (for fluent API support)
	 */
	public function setStat($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->stat !== $v) {
			$this->stat = $v;
			$this->modifiedColumns[] = PicturePeer::STAT;
		}

		return $this;
	} // setStat()

	/**
	 * Set the value of [cost] column.
	 * 
	 * @param      double $v new value
	 * @return     Picture The current object (for fluent API support)
	 */
	public function setCost($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->cost !== $v) {
			$this->cost = $v;
			$this->modifiedColumns[] = PicturePeer::COST;
		}

		return $this;
	} // setCost()

	/**
	 * Set the value of [name] column.
	 * 
	 * @param      string $v new value
	 * @return     Picture The current object (for fluent API support)
	 */
	public function setName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name !== $v) {
			$this->name = $v;
			$this->modifiedColumns[] = PicturePeer::NAME;
		}

		return $this;
	} // setName()

	/**
	 * Set the value of [modeid] column.
	 * 
	 * @param      int $v new value
	 * @return     Picture The current object (for fluent API support)
	 */
	public function setModeid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->modeid !== $v) {
			$this->modeid = $v;
			$this->modifiedColumns[] = PicturePeer::MODEID;
		}

		if ($this->aMode !== null && $this->aMode->getId() !== $v) {
			$this->aMode = null;
		}

		return $this;
	} // setModeid()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Picture The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = PicturePeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Picture The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = PicturePeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Set the value of [rank] column.
	 * 
	 * @param      int $v new value
	 * @return     Picture The current object (for fluent API support)
	 */
	public function setRank($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->rank !== $v || $this->isNew()) {
			$this->rank = $v;
			$this->modifiedColumns[] = PicturePeer::RANK;
		}

		return $this;
	} // setRank()

	/**
	 * Set the value of [privte] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Picture The current object (for fluent API support)
	 */
	public function setPrivte($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->privte !== $v) {
			$this->privte = $v;
			$this->modifiedColumns[] = PicturePeer::PRIVTE;
		}

		return $this;
	} // setPrivte()

	/**
	 * Set the value of [not_for_sale] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Picture The current object (for fluent API support)
	 */
	public function setNotForSale($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->not_for_sale !== $v) {
			$this->not_for_sale = $v;
			$this->modifiedColumns[] = PicturePeer::NOT_FOR_SALE;
		}

		return $this;
	} // setNotForSale()

	/**
	 * Set the value of [hidden] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Picture The current object (for fluent API support)
	 */
	public function setHidden($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->hidden !== $v) {
			$this->hidden = $v;
			$this->modifiedColumns[] = PicturePeer::HIDDEN;
		}

		return $this;
	} // setHidden()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->rank !== 0) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->content = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->userid = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->owner = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->stat = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->cost = ($row[$startcol + 5] !== null) ? (double) $row[$startcol + 5] : null;
			$this->name = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->modeid = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->created_at = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->updated_at = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->rank = ($row[$startcol + 10] !== null) ? (int) $row[$startcol + 10] : null;
			$this->privte = ($row[$startcol + 11] !== null) ? (boolean) $row[$startcol + 11] : null;
			$this->not_for_sale = ($row[$startcol + 12] !== null) ? (boolean) $row[$startcol + 12] : null;
			$this->hidden = ($row[$startcol + 13] !== null) ? (boolean) $row[$startcol + 13] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 14; // 14 = PicturePeer::NUM_COLUMNS - PicturePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Picture object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aUsrRelatedByUserid !== null && $this->userid !== $this->aUsrRelatedByUserid->getId()) {
			$this->aUsrRelatedByUserid = null;
		}
		if ($this->aUsrRelatedByOwner !== null && $this->owner !== $this->aUsrRelatedByOwner->getId()) {
			$this->aUsrRelatedByOwner = null;
		}
		if ($this->aMode !== null && $this->modeid !== $this->aMode->getId()) {
			$this->aMode = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PicturePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = PicturePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aUsrRelatedByUserid = null;
			$this->aUsrRelatedByOwner = null;
			$this->aMode = null;
			$this->collPictureComments = null;
			$this->lastPictureCommentCriteria = null;

			$this->collTests = null;
			$this->lastTestCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PicturePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePicture:delete:pre') as $callable)
			{
			  if ($ret = call_user_func($callable, $this, $con))
			  {
			    return;
			  }
			}

			if ($ret) {
				PicturePeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePicture:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PicturePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePicture:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(PicturePeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(PicturePeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePicture:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				$con->commit();
				PicturePeer::addInstanceToPool($this);
				return $affectedRows;
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUsrRelatedByUserid !== null) {
				if ($this->aUsrRelatedByUserid->isModified() || $this->aUsrRelatedByUserid->isNew()) {
					$affectedRows += $this->aUsrRelatedByUserid->save($con);
				}
				$this->setUsrRelatedByUserid($this->aUsrRelatedByUserid);
			}

			if ($this->aUsrRelatedByOwner !== null) {
				if ($this->aUsrRelatedByOwner->isModified() || $this->aUsrRelatedByOwner->isNew()) {
					$affectedRows += $this->aUsrRelatedByOwner->save($con);
				}
				$this->setUsrRelatedByOwner($this->aUsrRelatedByOwner);
			}

			if ($this->aMode !== null) {
				if ($this->aMode->isModified() || $this->aMode->isNew()) {
					$affectedRows += $this->aMode->save($con);
				}
				$this->setMode($this->aMode);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = PicturePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = PicturePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += PicturePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collPictureComments !== null) {
				foreach ($this->collPictureComments as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collTests !== null) {
				foreach ($this->collTests as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUsrRelatedByUserid !== null) {
				if (!$this->aUsrRelatedByUserid->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUsrRelatedByUserid->getValidationFailures());
				}
			}

			if ($this->aUsrRelatedByOwner !== null) {
				if (!$this->aUsrRelatedByOwner->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUsrRelatedByOwner->getValidationFailures());
				}
			}

			if ($this->aMode !== null) {
				if (!$this->aMode->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aMode->getValidationFailures());
				}
			}


			if (($retval = PicturePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collPictureComments !== null) {
					foreach ($this->collPictureComments as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collTests !== null) {
					foreach ($this->collTests as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PicturePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getContent();
				break;
			case 2:
				return $this->getUserid();
				break;
			case 3:
				return $this->getOwner();
				break;
			case 4:
				return $this->getStat();
				break;
			case 5:
				return $this->getCost();
				break;
			case 6:
				return $this->getName();
				break;
			case 7:
				return $this->getModeid();
				break;
			case 8:
				return $this->getCreatedAt();
				break;
			case 9:
				return $this->getUpdatedAt();
				break;
			case 10:
				return $this->getRank();
				break;
			case 11:
				return $this->getPrivte();
				break;
			case 12:
				return $this->getNotForSale();
				break;
			case 13:
				return $this->getHidden();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = PicturePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getContent(),
			$keys[2] => $this->getUserid(),
			$keys[3] => $this->getOwner(),
			$keys[4] => $this->getStat(),
			$keys[5] => $this->getCost(),
			$keys[6] => $this->getName(),
			$keys[7] => $this->getModeid(),
			$keys[8] => $this->getCreatedAt(),
			$keys[9] => $this->getUpdatedAt(),
			$keys[10] => $this->getRank(),
			$keys[11] => $this->getPrivte(),
			$keys[12] => $this->getNotForSale(),
			$keys[13] => $this->getHidden(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PicturePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setContent($value);
				break;
			case 2:
				$this->setUserid($value);
				break;
			case 3:
				$this->setOwner($value);
				break;
			case 4:
				$this->setStat($value);
				break;
			case 5:
				$this->setCost($value);
				break;
			case 6:
				$this->setName($value);
				break;
			case 7:
				$this->setModeid($value);
				break;
			case 8:
				$this->setCreatedAt($value);
				break;
			case 9:
				$this->setUpdatedAt($value);
				break;
			case 10:
				$this->setRank($value);
				break;
			case 11:
				$this->setPrivte($value);
				break;
			case 12:
				$this->setNotForSale($value);
				break;
			case 13:
				$this->setHidden($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = PicturePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setContent($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setUserid($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setOwner($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setStat($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setCost($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setName($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setModeid($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setCreatedAt($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setUpdatedAt($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setRank($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setPrivte($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setNotForSale($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setHidden($arr[$keys[13]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(PicturePeer::DATABASE_NAME);

		if ($this->isColumnModified(PicturePeer::ID)) $criteria->add(PicturePeer::ID, $this->id);
		if ($this->isColumnModified(PicturePeer::CONTENT)) $criteria->add(PicturePeer::CONTENT, $this->content);
		if ($this->isColumnModified(PicturePeer::USERID)) $criteria->add(PicturePeer::USERID, $this->userid);
		if ($this->isColumnModified(PicturePeer::OWNER)) $criteria->add(PicturePeer::OWNER, $this->owner);
		if ($this->isColumnModified(PicturePeer::STAT)) $criteria->add(PicturePeer::STAT, $this->stat);
		if ($this->isColumnModified(PicturePeer::COST)) $criteria->add(PicturePeer::COST, $this->cost);
		if ($this->isColumnModified(PicturePeer::NAME)) $criteria->add(PicturePeer::NAME, $this->name);
		if ($this->isColumnModified(PicturePeer::MODEID)) $criteria->add(PicturePeer::MODEID, $this->modeid);
		if ($this->isColumnModified(PicturePeer::CREATED_AT)) $criteria->add(PicturePeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(PicturePeer::UPDATED_AT)) $criteria->add(PicturePeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(PicturePeer::RANK)) $criteria->add(PicturePeer::RANK, $this->rank);
		if ($this->isColumnModified(PicturePeer::PRIVTE)) $criteria->add(PicturePeer::PRIVTE, $this->privte);
		if ($this->isColumnModified(PicturePeer::NOT_FOR_SALE)) $criteria->add(PicturePeer::NOT_FOR_SALE, $this->not_for_sale);
		if ($this->isColumnModified(PicturePeer::HIDDEN)) $criteria->add(PicturePeer::HIDDEN, $this->hidden);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(PicturePeer::DATABASE_NAME);

		$criteria->add(PicturePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Picture (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setContent($this->content);

		$copyObj->setUserid($this->userid);

		$copyObj->setOwner($this->owner);

		$copyObj->setStat($this->stat);

		$copyObj->setCost($this->cost);

		$copyObj->setName($this->name);

		$copyObj->setModeid($this->modeid);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);

		$copyObj->setRank($this->rank);

		$copyObj->setPrivte($this->privte);

		$copyObj->setNotForSale($this->not_for_sale);

		$copyObj->setHidden($this->hidden);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getPictureComments() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPictureComment($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getTests() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTest($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Picture Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     PicturePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new PicturePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Usr object.
	 *
	 * @param      Usr $v
	 * @return     Picture The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUsrRelatedByUserid(Usr $v = null)
	{
		if ($v === null) {
			$this->setUserid(NULL);
		} else {
			$this->setUserid($v->getId());
		}

		$this->aUsrRelatedByUserid = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Usr object, it will not be re-added.
		if ($v !== null) {
			$v->addPictureRelatedByUserid($this);
		}

		return $this;
	}


	/**
	 * Get the associated Usr object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Usr The associated Usr object.
	 * @throws     PropelException
	 */
	public function getUsrRelatedByUserid(PropelPDO $con = null)
	{
		if ($this->aUsrRelatedByUserid === null && ($this->userid !== null)) {
			$this->aUsrRelatedByUserid = UsrPeer::retrieveByPk($this->userid);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUsrRelatedByUserid->addPicturesRelatedByUserid($this);
			 */
		}
		return $this->aUsrRelatedByUserid;
	}

	/**
	 * Declares an association between this object and a Usr object.
	 *
	 * @param      Usr $v
	 * @return     Picture The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUsrRelatedByOwner(Usr $v = null)
	{
		if ($v === null) {
			$this->setOwner(NULL);
		} else {
			$this->setOwner($v->getId());
		}

		$this->aUsrRelatedByOwner = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Usr object, it will not be re-added.
		if ($v !== null) {
			$v->addPictureRelatedByOwner($this);
		}

		return $this;
	}


	/**
	 * Get the associated Usr object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Usr The associated Usr object.
	 * @throws     PropelException
	 */
	public function getUsrRelatedByOwner(PropelPDO $con = null)
	{
		if ($this->aUsrRelatedByOwner === null && ($this->owner !== null)) {
			$this->aUsrRelatedByOwner = UsrPeer::retrieveByPk($this->owner);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUsrRelatedByOwner->addPicturesRelatedByOwner($this);
			 */
		}
		return $this->aUsrRelatedByOwner;
	}

	/**
	 * Declares an association between this object and a Mode object.
	 *
	 * @param      Mode $v
	 * @return     Picture The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setMode(Mode $v = null)
	{
		if ($v === null) {
			$this->setModeid(NULL);
		} else {
			$this->setModeid($v->getId());
		}

		$this->aMode = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Mode object, it will not be re-added.
		if ($v !== null) {
			$v->addPicture($this);
		}

		return $this;
	}


	/**
	 * Get the associated Mode object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Mode The associated Mode object.
	 * @throws     PropelException
	 */
	public function getMode(PropelPDO $con = null)
	{
		if ($this->aMode === null && ($this->modeid !== null)) {
			$this->aMode = ModePeer::retrieveByPk($this->modeid);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aMode->addPictures($this);
			 */
		}
		return $this->aMode;
	}

	/**
	 * Clears out the collPictureComments collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPictureComments()
	 */
	public function clearPictureComments()
	{
		$this->collPictureComments = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPictureComments collection (array).
	 *
	 * By default this just sets the collPictureComments collection to an empty array (like clearcollPictureComments());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPictureComments()
	{
		$this->collPictureComments = array();
	}

	/**
	 * Gets an array of PictureComment objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Picture has previously been saved, it will retrieve
	 * related PictureComments from storage. If this Picture is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array PictureComment[]
	 * @throws     PropelException
	 */
	public function getPictureComments($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PicturePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPictureComments === null) {
			if ($this->isNew()) {
			   $this->collPictureComments = array();
			} else {

				$criteria->add(PictureCommentPeer::PICTUREID, $this->id);

				PictureCommentPeer::addSelectColumns($criteria);
				$this->collPictureComments = PictureCommentPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(PictureCommentPeer::PICTUREID, $this->id);

				PictureCommentPeer::addSelectColumns($criteria);
				if (!isset($this->lastPictureCommentCriteria) || !$this->lastPictureCommentCriteria->equals($criteria)) {
					$this->collPictureComments = PictureCommentPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastPictureCommentCriteria = $criteria;
		return $this->collPictureComments;
	}

	/**
	 * Returns the number of related PictureComment objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related PictureComment objects.
	 * @throws     PropelException
	 */
	public function countPictureComments(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PicturePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collPictureComments === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(PictureCommentPeer::PICTUREID, $this->id);

				$count = PictureCommentPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(PictureCommentPeer::PICTUREID, $this->id);

				if (!isset($this->lastPictureCommentCriteria) || !$this->lastPictureCommentCriteria->equals($criteria)) {
					$count = PictureCommentPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collPictureComments);
				}
			} else {
				$count = count($this->collPictureComments);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a PictureComment object to this object
	 * through the PictureComment foreign key attribute.
	 *
	 * @param      PictureComment $l PictureComment
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPictureComment(PictureComment $l)
	{
		if ($this->collPictureComments === null) {
			$this->initPictureComments();
		}
		if (!in_array($l, $this->collPictureComments, true)) { // only add it if the **same** object is not already associated
			array_push($this->collPictureComments, $l);
			$l->setPicture($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Picture is new, it will return
	 * an empty collection; or if this Picture has previously
	 * been saved, it will retrieve related PictureComments from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Picture.
	 */
	public function getPictureCommentsJoinUsr($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PicturePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPictureComments === null) {
			if ($this->isNew()) {
				$this->collPictureComments = array();
			} else {

				$criteria->add(PictureCommentPeer::PICTUREID, $this->id);

				$this->collPictureComments = PictureCommentPeer::doSelectJoinUsr($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PictureCommentPeer::PICTUREID, $this->id);

			if (!isset($this->lastPictureCommentCriteria) || !$this->lastPictureCommentCriteria->equals($criteria)) {
				$this->collPictureComments = PictureCommentPeer::doSelectJoinUsr($criteria, $con, $join_behavior);
			}
		}
		$this->lastPictureCommentCriteria = $criteria;

		return $this->collPictureComments;
	}

	/**
	 * Clears out the collTests collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTests()
	 */
	public function clearTests()
	{
		$this->collTests = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTests collection (array).
	 *
	 * By default this just sets the collTests collection to an empty array (like clearcollTests());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initTests()
	{
		$this->collTests = array();
	}

	/**
	 * Gets an array of Test objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Picture has previously been saved, it will retrieve
	 * related Tests from storage. If this Picture is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Test[]
	 * @throws     PropelException
	 */
	public function getTests($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PicturePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTests === null) {
			if ($this->isNew()) {
			   $this->collTests = array();
			} else {

				$criteria->add(TestPeer::TASKID, $this->id);

				TestPeer::addSelectColumns($criteria);
				$this->collTests = TestPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(TestPeer::TASKID, $this->id);

				TestPeer::addSelectColumns($criteria);
				if (!isset($this->lastTestCriteria) || !$this->lastTestCriteria->equals($criteria)) {
					$this->collTests = TestPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastTestCriteria = $criteria;
		return $this->collTests;
	}

	/**
	 * Returns the number of related Test objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Test objects.
	 * @throws     PropelException
	 */
	public function countTests(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PicturePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collTests === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(TestPeer::TASKID, $this->id);

				$count = TestPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(TestPeer::TASKID, $this->id);

				if (!isset($this->lastTestCriteria) || !$this->lastTestCriteria->equals($criteria)) {
					$count = TestPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collTests);
				}
			} else {
				$count = count($this->collTests);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Test object to this object
	 * through the Test foreign key attribute.
	 *
	 * @param      Test $l Test
	 * @return     void
	 * @throws     PropelException
	 */
	public function addTest(Test $l)
	{
		if ($this->collTests === null) {
			$this->initTests();
		}
		if (!in_array($l, $this->collTests, true)) { // only add it if the **same** object is not already associated
			array_push($this->collTests, $l);
			$l->setPicture($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Picture is new, it will return
	 * an empty collection; or if this Picture has previously
	 * been saved, it will retrieve related Tests from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Picture.
	 */
	public function getTestsJoinUsr($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PicturePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTests === null) {
			if ($this->isNew()) {
				$this->collTests = array();
			} else {

				$criteria->add(TestPeer::TASKID, $this->id);

				$this->collTests = TestPeer::doSelectJoinUsr($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(TestPeer::TASKID, $this->id);

			if (!isset($this->lastTestCriteria) || !$this->lastTestCriteria->equals($criteria)) {
				$this->collTests = TestPeer::doSelectJoinUsr($criteria, $con, $join_behavior);
			}
		}
		$this->lastTestCriteria = $criteria;

		return $this->collTests;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collPictureComments) {
				foreach ((array) $this->collPictureComments as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collTests) {
				foreach ((array) $this->collTests as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collPictureComments = null;
		$this->collTests = null;
			$this->aUsrRelatedByUserid = null;
			$this->aUsrRelatedByOwner = null;
			$this->aMode = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BasePicture:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BasePicture::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BasePicture
