<?php

/**
 * Base class that represents a row from the 'task' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0-dev on:
 *
 * Wed Mar 31 16:35:31 2010
 *
 * @package    lib.model.om
 */
abstract class BaseTask extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        TaskPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the userid field.
	 * @var        int
	 */
	protected $userid;

	/**
	 * The value for the authorid field.
	 * @var        int
	 */
	protected $authorid;

	/**
	 * The value for the title field.
	 * @var        string
	 */
	protected $title;

	/**
	 * The value for the content field.
	 * @var        string
	 */
	protected $content;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the rank field.
	 * @var        int
	 */
	protected $rank;

	/**
	 * The value for the hidden field.
	 * @var        boolean
	 */
	protected $hidden;

	/**
	 * The value for the statid field.
	 * @var        int
	 */
	protected $statid;

	/**
	 * The value for the urgencyid field.
	 * @var        int
	 */
	protected $urgencyid;

	/**
	 * @var        Usr
	 */
	protected $aUsrRelatedByUserid;

	/**
	 * @var        Usr
	 */
	protected $aUsrRelatedByAuthorid;

	/**
	 * @var        Stat
	 */
	protected $aStat;

	/**
	 * @var        Urgency
	 */
	protected $aUrgency;

	/**
	 * @var        array TaskComment[] Collection to store aggregation of TaskComment objects.
	 */
	protected $collTaskComments;

	/**
	 * @var        Criteria The criteria used to select the current contents of collTaskComments.
	 */
	private $lastTaskCommentCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'TaskPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [userid] column value.
	 * 
	 * @return     int
	 */
	public function getUserid()
	{
		return $this->userid;
	}

	/**
	 * Get the [authorid] column value.
	 * 
	 * @return     int
	 */
	public function getAuthorid()
	{
		return $this->authorid;
	}

	/**
	 * Get the [title] column value.
	 * 
	 * @return     string
	 */
	public function getTitle()
	{
		return $this->title;
	}

	/**
	 * Get the [content] column value.
	 * 
	 * @return     string
	 */
	public function getContent()
	{
		return $this->content;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->created_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->updated_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [rank] column value.
	 * 
	 * @return     int
	 */
	public function getRank()
	{
		return $this->rank;
	}

	/**
	 * Get the [hidden] column value.
	 * 
	 * @return     boolean
	 */
	public function getHidden()
	{
		return $this->hidden;
	}

	/**
	 * Get the [statid] column value.
	 * 
	 * @return     int
	 */
	public function getStatid()
	{
		return $this->statid;
	}

	/**
	 * Get the [urgencyid] column value.
	 * 
	 * @return     int
	 */
	public function getUrgencyid()
	{
		return $this->urgencyid;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Task The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = TaskPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [userid] column.
	 * 
	 * @param      int $v new value
	 * @return     Task The current object (for fluent API support)
	 */
	public function setUserid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->userid !== $v) {
			$this->userid = $v;
			$this->modifiedColumns[] = TaskPeer::USERID;
		}

		if ($this->aUsrRelatedByUserid !== null && $this->aUsrRelatedByUserid->getId() !== $v) {
			$this->aUsrRelatedByUserid = null;
		}

		return $this;
	} // setUserid()

	/**
	 * Set the value of [authorid] column.
	 * 
	 * @param      int $v new value
	 * @return     Task The current object (for fluent API support)
	 */
	public function setAuthorid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->authorid !== $v) {
			$this->authorid = $v;
			$this->modifiedColumns[] = TaskPeer::AUTHORID;
		}

		if ($this->aUsrRelatedByAuthorid !== null && $this->aUsrRelatedByAuthorid->getId() !== $v) {
			$this->aUsrRelatedByAuthorid = null;
		}

		return $this;
	} // setAuthorid()

	/**
	 * Set the value of [title] column.
	 * 
	 * @param      string $v new value
	 * @return     Task The current object (for fluent API support)
	 */
	public function setTitle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->title !== $v) {
			$this->title = $v;
			$this->modifiedColumns[] = TaskPeer::TITLE;
		}

		return $this;
	} // setTitle()

	/**
	 * Set the value of [content] column.
	 * 
	 * @param      string $v new value
	 * @return     Task The current object (for fluent API support)
	 */
	public function setContent($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->content !== $v) {
			$this->content = $v;
			$this->modifiedColumns[] = TaskPeer::CONTENT;
		}

		return $this;
	} // setContent()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Task The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = TaskPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Task The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = TaskPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Set the value of [rank] column.
	 * 
	 * @param      int $v new value
	 * @return     Task The current object (for fluent API support)
	 */
	public function setRank($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->rank !== $v) {
			$this->rank = $v;
			$this->modifiedColumns[] = TaskPeer::RANK;
		}

		return $this;
	} // setRank()

	/**
	 * Set the value of [hidden] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Task The current object (for fluent API support)
	 */
	public function setHidden($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->hidden !== $v) {
			$this->hidden = $v;
			$this->modifiedColumns[] = TaskPeer::HIDDEN;
		}

		return $this;
	} // setHidden()

	/**
	 * Set the value of [statid] column.
	 * 
	 * @param      int $v new value
	 * @return     Task The current object (for fluent API support)
	 */
	public function setStatid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->statid !== $v) {
			$this->statid = $v;
			$this->modifiedColumns[] = TaskPeer::STATID;
		}

		if ($this->aStat !== null && $this->aStat->getId() !== $v) {
			$this->aStat = null;
		}

		return $this;
	} // setStatid()

	/**
	 * Set the value of [urgencyid] column.
	 * 
	 * @param      int $v new value
	 * @return     Task The current object (for fluent API support)
	 */
	public function setUrgencyid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->urgencyid !== $v) {
			$this->urgencyid = $v;
			$this->modifiedColumns[] = TaskPeer::URGENCYID;
		}

		if ($this->aUrgency !== null && $this->aUrgency->getId() !== $v) {
			$this->aUrgency = null;
		}

		return $this;
	} // setUrgencyid()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->userid = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->authorid = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->title = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->content = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->created_at = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->updated_at = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->rank = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->hidden = ($row[$startcol + 8] !== null) ? (boolean) $row[$startcol + 8] : null;
			$this->statid = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->urgencyid = ($row[$startcol + 10] !== null) ? (int) $row[$startcol + 10] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 11; // 11 = TaskPeer::NUM_COLUMNS - TaskPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Task object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aUsrRelatedByUserid !== null && $this->userid !== $this->aUsrRelatedByUserid->getId()) {
			$this->aUsrRelatedByUserid = null;
		}
		if ($this->aUsrRelatedByAuthorid !== null && $this->authorid !== $this->aUsrRelatedByAuthorid->getId()) {
			$this->aUsrRelatedByAuthorid = null;
		}
		if ($this->aStat !== null && $this->statid !== $this->aStat->getId()) {
			$this->aStat = null;
		}
		if ($this->aUrgency !== null && $this->urgencyid !== $this->aUrgency->getId()) {
			$this->aUrgency = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TaskPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = TaskPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aUsrRelatedByUserid = null;
			$this->aUsrRelatedByAuthorid = null;
			$this->aStat = null;
			$this->aUrgency = null;
			$this->collTaskComments = null;
			$this->lastTaskCommentCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TaskPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseTask:delete:pre') as $callable)
			{
			  if ($ret = call_user_func($callable, $this, $con))
			  {
			    return;
			  }
			}

			if ($ret) {
				TaskPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseTask:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(TaskPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseTask:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(TaskPeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(TaskPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseTask:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				$con->commit();
				TaskPeer::addInstanceToPool($this);
				return $affectedRows;
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUsrRelatedByUserid !== null) {
				if ($this->aUsrRelatedByUserid->isModified() || $this->aUsrRelatedByUserid->isNew()) {
					$affectedRows += $this->aUsrRelatedByUserid->save($con);
				}
				$this->setUsrRelatedByUserid($this->aUsrRelatedByUserid);
			}

			if ($this->aUsrRelatedByAuthorid !== null) {
				if ($this->aUsrRelatedByAuthorid->isModified() || $this->aUsrRelatedByAuthorid->isNew()) {
					$affectedRows += $this->aUsrRelatedByAuthorid->save($con);
				}
				$this->setUsrRelatedByAuthorid($this->aUsrRelatedByAuthorid);
			}

			if ($this->aStat !== null) {
				if ($this->aStat->isModified() || $this->aStat->isNew()) {
					$affectedRows += $this->aStat->save($con);
				}
				$this->setStat($this->aStat);
			}

			if ($this->aUrgency !== null) {
				if ($this->aUrgency->isModified() || $this->aUrgency->isNew()) {
					$affectedRows += $this->aUrgency->save($con);
				}
				$this->setUrgency($this->aUrgency);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = TaskPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = TaskPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += TaskPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collTaskComments !== null) {
				foreach ($this->collTaskComments as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUsrRelatedByUserid !== null) {
				if (!$this->aUsrRelatedByUserid->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUsrRelatedByUserid->getValidationFailures());
				}
			}

			if ($this->aUsrRelatedByAuthorid !== null) {
				if (!$this->aUsrRelatedByAuthorid->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUsrRelatedByAuthorid->getValidationFailures());
				}
			}

			if ($this->aStat !== null) {
				if (!$this->aStat->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aStat->getValidationFailures());
				}
			}

			if ($this->aUrgency !== null) {
				if (!$this->aUrgency->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUrgency->getValidationFailures());
				}
			}


			if (($retval = TaskPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collTaskComments !== null) {
					foreach ($this->collTaskComments as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TaskPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getUserid();
				break;
			case 2:
				return $this->getAuthorid();
				break;
			case 3:
				return $this->getTitle();
				break;
			case 4:
				return $this->getContent();
				break;
			case 5:
				return $this->getCreatedAt();
				break;
			case 6:
				return $this->getUpdatedAt();
				break;
			case 7:
				return $this->getRank();
				break;
			case 8:
				return $this->getHidden();
				break;
			case 9:
				return $this->getStatid();
				break;
			case 10:
				return $this->getUrgencyid();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = TaskPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getUserid(),
			$keys[2] => $this->getAuthorid(),
			$keys[3] => $this->getTitle(),
			$keys[4] => $this->getContent(),
			$keys[5] => $this->getCreatedAt(),
			$keys[6] => $this->getUpdatedAt(),
			$keys[7] => $this->getRank(),
			$keys[8] => $this->getHidden(),
			$keys[9] => $this->getStatid(),
			$keys[10] => $this->getUrgencyid(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = TaskPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setUserid($value);
				break;
			case 2:
				$this->setAuthorid($value);
				break;
			case 3:
				$this->setTitle($value);
				break;
			case 4:
				$this->setContent($value);
				break;
			case 5:
				$this->setCreatedAt($value);
				break;
			case 6:
				$this->setUpdatedAt($value);
				break;
			case 7:
				$this->setRank($value);
				break;
			case 8:
				$this->setHidden($value);
				break;
			case 9:
				$this->setStatid($value);
				break;
			case 10:
				$this->setUrgencyid($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = TaskPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setUserid($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setAuthorid($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setTitle($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setContent($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setCreatedAt($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setUpdatedAt($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setRank($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setHidden($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setStatid($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setUrgencyid($arr[$keys[10]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(TaskPeer::DATABASE_NAME);

		if ($this->isColumnModified(TaskPeer::ID)) $criteria->add(TaskPeer::ID, $this->id);
		if ($this->isColumnModified(TaskPeer::USERID)) $criteria->add(TaskPeer::USERID, $this->userid);
		if ($this->isColumnModified(TaskPeer::AUTHORID)) $criteria->add(TaskPeer::AUTHORID, $this->authorid);
		if ($this->isColumnModified(TaskPeer::TITLE)) $criteria->add(TaskPeer::TITLE, $this->title);
		if ($this->isColumnModified(TaskPeer::CONTENT)) $criteria->add(TaskPeer::CONTENT, $this->content);
		if ($this->isColumnModified(TaskPeer::CREATED_AT)) $criteria->add(TaskPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(TaskPeer::UPDATED_AT)) $criteria->add(TaskPeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(TaskPeer::RANK)) $criteria->add(TaskPeer::RANK, $this->rank);
		if ($this->isColumnModified(TaskPeer::HIDDEN)) $criteria->add(TaskPeer::HIDDEN, $this->hidden);
		if ($this->isColumnModified(TaskPeer::STATID)) $criteria->add(TaskPeer::STATID, $this->statid);
		if ($this->isColumnModified(TaskPeer::URGENCYID)) $criteria->add(TaskPeer::URGENCYID, $this->urgencyid);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(TaskPeer::DATABASE_NAME);

		$criteria->add(TaskPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Task (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setUserid($this->userid);

		$copyObj->setAuthorid($this->authorid);

		$copyObj->setTitle($this->title);

		$copyObj->setContent($this->content);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);

		$copyObj->setRank($this->rank);

		$copyObj->setHidden($this->hidden);

		$copyObj->setStatid($this->statid);

		$copyObj->setUrgencyid($this->urgencyid);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getTaskComments() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTaskComment($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Task Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     TaskPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new TaskPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Usr object.
	 *
	 * @param      Usr $v
	 * @return     Task The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUsrRelatedByUserid(Usr $v = null)
	{
		if ($v === null) {
			$this->setUserid(NULL);
		} else {
			$this->setUserid($v->getId());
		}

		$this->aUsrRelatedByUserid = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Usr object, it will not be re-added.
		if ($v !== null) {
			$v->addTaskRelatedByUserid($this);
		}

		return $this;
	}


	/**
	 * Get the associated Usr object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Usr The associated Usr object.
	 * @throws     PropelException
	 */
	public function getUsrRelatedByUserid(PropelPDO $con = null)
	{
		if ($this->aUsrRelatedByUserid === null && ($this->userid !== null)) {
			$this->aUsrRelatedByUserid = UsrPeer::retrieveByPk($this->userid);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUsrRelatedByUserid->addTasksRelatedByUserid($this);
			 */
		}
		return $this->aUsrRelatedByUserid;
	}

	/**
	 * Declares an association between this object and a Usr object.
	 *
	 * @param      Usr $v
	 * @return     Task The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUsrRelatedByAuthorid(Usr $v = null)
	{
		if ($v === null) {
			$this->setAuthorid(NULL);
		} else {
			$this->setAuthorid($v->getId());
		}

		$this->aUsrRelatedByAuthorid = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Usr object, it will not be re-added.
		if ($v !== null) {
			$v->addTaskRelatedByAuthorid($this);
		}

		return $this;
	}


	/**
	 * Get the associated Usr object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Usr The associated Usr object.
	 * @throws     PropelException
	 */
	public function getUsrRelatedByAuthorid(PropelPDO $con = null)
	{
		if ($this->aUsrRelatedByAuthorid === null && ($this->authorid !== null)) {
			$this->aUsrRelatedByAuthorid = UsrPeer::retrieveByPk($this->authorid);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUsrRelatedByAuthorid->addTasksRelatedByAuthorid($this);
			 */
		}
		return $this->aUsrRelatedByAuthorid;
	}

	/**
	 * Declares an association between this object and a Stat object.
	 *
	 * @param      Stat $v
	 * @return     Task The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setStat(Stat $v = null)
	{
		if ($v === null) {
			$this->setStatid(NULL);
		} else {
			$this->setStatid($v->getId());
		}

		$this->aStat = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Stat object, it will not be re-added.
		if ($v !== null) {
			$v->addTask($this);
		}

		return $this;
	}


	/**
	 * Get the associated Stat object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Stat The associated Stat object.
	 * @throws     PropelException
	 */
	public function getStat(PropelPDO $con = null)
	{
		if ($this->aStat === null && ($this->statid !== null)) {
			$this->aStat = StatPeer::retrieveByPk($this->statid);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aStat->addTasks($this);
			 */
		}
		return $this->aStat;
	}

	/**
	 * Declares an association between this object and a Urgency object.
	 *
	 * @param      Urgency $v
	 * @return     Task The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUrgency(Urgency $v = null)
	{
		if ($v === null) {
			$this->setUrgencyid(NULL);
		} else {
			$this->setUrgencyid($v->getId());
		}

		$this->aUrgency = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Urgency object, it will not be re-added.
		if ($v !== null) {
			$v->addTask($this);
		}

		return $this;
	}


	/**
	 * Get the associated Urgency object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Urgency The associated Urgency object.
	 * @throws     PropelException
	 */
	public function getUrgency(PropelPDO $con = null)
	{
		if ($this->aUrgency === null && ($this->urgencyid !== null)) {
			$this->aUrgency = UrgencyPeer::retrieveByPk($this->urgencyid);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUrgency->addTasks($this);
			 */
		}
		return $this->aUrgency;
	}

	/**
	 * Clears out the collTaskComments collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTaskComments()
	 */
	public function clearTaskComments()
	{
		$this->collTaskComments = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTaskComments collection (array).
	 *
	 * By default this just sets the collTaskComments collection to an empty array (like clearcollTaskComments());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initTaskComments()
	{
		$this->collTaskComments = array();
	}

	/**
	 * Gets an array of TaskComment objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Task has previously been saved, it will retrieve
	 * related TaskComments from storage. If this Task is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array TaskComment[]
	 * @throws     PropelException
	 */
	public function getTaskComments($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TaskPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTaskComments === null) {
			if ($this->isNew()) {
			   $this->collTaskComments = array();
			} else {

				$criteria->add(TaskCommentPeer::TASKID, $this->id);

				TaskCommentPeer::addSelectColumns($criteria);
				$this->collTaskComments = TaskCommentPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(TaskCommentPeer::TASKID, $this->id);

				TaskCommentPeer::addSelectColumns($criteria);
				if (!isset($this->lastTaskCommentCriteria) || !$this->lastTaskCommentCriteria->equals($criteria)) {
					$this->collTaskComments = TaskCommentPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastTaskCommentCriteria = $criteria;
		return $this->collTaskComments;
	}

	/**
	 * Returns the number of related TaskComment objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related TaskComment objects.
	 * @throws     PropelException
	 */
	public function countTaskComments(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TaskPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collTaskComments === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(TaskCommentPeer::TASKID, $this->id);

				$count = TaskCommentPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(TaskCommentPeer::TASKID, $this->id);

				if (!isset($this->lastTaskCommentCriteria) || !$this->lastTaskCommentCriteria->equals($criteria)) {
					$count = TaskCommentPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collTaskComments);
				}
			} else {
				$count = count($this->collTaskComments);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a TaskComment object to this object
	 * through the TaskComment foreign key attribute.
	 *
	 * @param      TaskComment $l TaskComment
	 * @return     void
	 * @throws     PropelException
	 */
	public function addTaskComment(TaskComment $l)
	{
		if ($this->collTaskComments === null) {
			$this->initTaskComments();
		}
		if (!in_array($l, $this->collTaskComments, true)) { // only add it if the **same** object is not already associated
			array_push($this->collTaskComments, $l);
			$l->setTask($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Task is new, it will return
	 * an empty collection; or if this Task has previously
	 * been saved, it will retrieve related TaskComments from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Task.
	 */
	public function getTaskCommentsJoinUsr($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(TaskPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTaskComments === null) {
			if ($this->isNew()) {
				$this->collTaskComments = array();
			} else {

				$criteria->add(TaskCommentPeer::TASKID, $this->id);

				$this->collTaskComments = TaskCommentPeer::doSelectJoinUsr($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(TaskCommentPeer::TASKID, $this->id);

			if (!isset($this->lastTaskCommentCriteria) || !$this->lastTaskCommentCriteria->equals($criteria)) {
				$this->collTaskComments = TaskCommentPeer::doSelectJoinUsr($criteria, $con, $join_behavior);
			}
		}
		$this->lastTaskCommentCriteria = $criteria;

		return $this->collTaskComments;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collTaskComments) {
				foreach ((array) $this->collTaskComments as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collTaskComments = null;
			$this->aUsrRelatedByUserid = null;
			$this->aUsrRelatedByAuthorid = null;
			$this->aStat = null;
			$this->aUrgency = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseTask:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseTask::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseTask
