<?php

/**
 * Base class that represents a row from the 'blog' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0-dev on:
 *
 * Wed Mar 31 16:35:30 2010
 *
 * @package    lib.model.om
 */
abstract class BaseBlog extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        BlogPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the userid field.
	 * @var        int
	 */
	protected $userid;

	/**
	 * The value for the title field.
	 * @var        string
	 */
	protected $title;

	/**
	 * The value for the content field.
	 * @var        string
	 */
	protected $content;

	/**
	 * The value for the spic field.
	 * @var        int
	 */
	protected $spic;

	/**
	 * The value for the rank field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $rank;

	/**
	 * The value for the hidden field.
	 * @var        boolean
	 */
	protected $hidden;

	/**
	 * The value for the modeid field.
	 * @var        int
	 */
	protected $modeid;

	/**
	 * @var        Usr
	 */
	protected $aUsr;

	/**
	 * @var        SysPic
	 */
	protected $aSysPic;

	/**
	 * @var        Mode
	 */
	protected $aMode;

	/**
	 * @var        array BlogComment[] Collection to store aggregation of BlogComment objects.
	 */
	protected $collBlogComments;

	/**
	 * @var        Criteria The criteria used to select the current contents of collBlogComments.
	 */
	private $lastBlogCommentCriteria = null;

	/**
	 * @var        array Post[] Collection to store aggregation of Post objects.
	 */
	protected $collPosts;

	/**
	 * @var        Criteria The criteria used to select the current contents of collPosts.
	 */
	private $lastPostCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'BlogPeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->rank = 0;
	}

	/**
	 * Initializes internal state of BaseBlog object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [userid] column value.
	 * 
	 * @return     int
	 */
	public function getUserid()
	{
		return $this->userid;
	}

	/**
	 * Get the [title] column value.
	 * 
	 * @return     string
	 */
	public function getTitle()
	{
		return $this->title;
	}

	/**
	 * Get the [content] column value.
	 * 
	 * @return     string
	 */
	public function getContent()
	{
		return $this->content;
	}

	/**
	 * Get the [spic] column value.
	 * 
	 * @return     int
	 */
	public function getSpic()
	{
		return $this->spic;
	}

	/**
	 * Get the [rank] column value.
	 * 
	 * @return     int
	 */
	public function getRank()
	{
		return $this->rank;
	}

	/**
	 * Get the [hidden] column value.
	 * 
	 * @return     boolean
	 */
	public function getHidden()
	{
		return $this->hidden;
	}

	/**
	 * Get the [modeid] column value.
	 * 
	 * @return     int
	 */
	public function getModeid()
	{
		return $this->modeid;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Blog The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = BlogPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [userid] column.
	 * 
	 * @param      int $v new value
	 * @return     Blog The current object (for fluent API support)
	 */
	public function setUserid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->userid !== $v) {
			$this->userid = $v;
			$this->modifiedColumns[] = BlogPeer::USERID;
		}

		if ($this->aUsr !== null && $this->aUsr->getId() !== $v) {
			$this->aUsr = null;
		}

		return $this;
	} // setUserid()

	/**
	 * Set the value of [title] column.
	 * 
	 * @param      string $v new value
	 * @return     Blog The current object (for fluent API support)
	 */
	public function setTitle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->title !== $v) {
			$this->title = $v;
			$this->modifiedColumns[] = BlogPeer::TITLE;
		}

		return $this;
	} // setTitle()

	/**
	 * Set the value of [content] column.
	 * 
	 * @param      string $v new value
	 * @return     Blog The current object (for fluent API support)
	 */
	public function setContent($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->content !== $v) {
			$this->content = $v;
			$this->modifiedColumns[] = BlogPeer::CONTENT;
		}

		return $this;
	} // setContent()

	/**
	 * Set the value of [spic] column.
	 * 
	 * @param      int $v new value
	 * @return     Blog The current object (for fluent API support)
	 */
	public function setSpic($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->spic !== $v) {
			$this->spic = $v;
			$this->modifiedColumns[] = BlogPeer::SPIC;
		}

		if ($this->aSysPic !== null && $this->aSysPic->getId() !== $v) {
			$this->aSysPic = null;
		}

		return $this;
	} // setSpic()

	/**
	 * Set the value of [rank] column.
	 * 
	 * @param      int $v new value
	 * @return     Blog The current object (for fluent API support)
	 */
	public function setRank($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->rank !== $v || $this->isNew()) {
			$this->rank = $v;
			$this->modifiedColumns[] = BlogPeer::RANK;
		}

		return $this;
	} // setRank()

	/**
	 * Set the value of [hidden] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Blog The current object (for fluent API support)
	 */
	public function setHidden($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->hidden !== $v) {
			$this->hidden = $v;
			$this->modifiedColumns[] = BlogPeer::HIDDEN;
		}

		return $this;
	} // setHidden()

	/**
	 * Set the value of [modeid] column.
	 * 
	 * @param      int $v new value
	 * @return     Blog The current object (for fluent API support)
	 */
	public function setModeid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->modeid !== $v) {
			$this->modeid = $v;
			$this->modifiedColumns[] = BlogPeer::MODEID;
		}

		if ($this->aMode !== null && $this->aMode->getId() !== $v) {
			$this->aMode = null;
		}

		return $this;
	} // setModeid()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->rank !== 0) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->userid = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->title = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->content = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->spic = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->rank = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->hidden = ($row[$startcol + 6] !== null) ? (boolean) $row[$startcol + 6] : null;
			$this->modeid = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 8; // 8 = BlogPeer::NUM_COLUMNS - BlogPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Blog object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aUsr !== null && $this->userid !== $this->aUsr->getId()) {
			$this->aUsr = null;
		}
		if ($this->aSysPic !== null && $this->spic !== $this->aSysPic->getId()) {
			$this->aSysPic = null;
		}
		if ($this->aMode !== null && $this->modeid !== $this->aMode->getId()) {
			$this->aMode = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(BlogPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = BlogPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aUsr = null;
			$this->aSysPic = null;
			$this->aMode = null;
			$this->collBlogComments = null;
			$this->lastBlogCommentCriteria = null;

			$this->collPosts = null;
			$this->lastPostCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(BlogPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseBlog:delete:pre') as $callable)
			{
			  if ($ret = call_user_func($callable, $this, $con))
			  {
			    return;
			  }
			}

			if ($ret) {
				BlogPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseBlog:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(BlogPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseBlog:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseBlog:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				$con->commit();
				BlogPeer::addInstanceToPool($this);
				return $affectedRows;
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUsr !== null) {
				if ($this->aUsr->isModified() || $this->aUsr->isNew()) {
					$affectedRows += $this->aUsr->save($con);
				}
				$this->setUsr($this->aUsr);
			}

			if ($this->aSysPic !== null) {
				if ($this->aSysPic->isModified() || $this->aSysPic->isNew()) {
					$affectedRows += $this->aSysPic->save($con);
				}
				$this->setSysPic($this->aSysPic);
			}

			if ($this->aMode !== null) {
				if ($this->aMode->isModified() || $this->aMode->isNew()) {
					$affectedRows += $this->aMode->save($con);
				}
				$this->setMode($this->aMode);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = BlogPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = BlogPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += BlogPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collBlogComments !== null) {
				foreach ($this->collBlogComments as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collPosts !== null) {
				foreach ($this->collPosts as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aUsr !== null) {
				if (!$this->aUsr->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aUsr->getValidationFailures());
				}
			}

			if ($this->aSysPic !== null) {
				if (!$this->aSysPic->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aSysPic->getValidationFailures());
				}
			}

			if ($this->aMode !== null) {
				if (!$this->aMode->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aMode->getValidationFailures());
				}
			}


			if (($retval = BlogPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collBlogComments !== null) {
					foreach ($this->collBlogComments as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collPosts !== null) {
					foreach ($this->collPosts as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = BlogPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getUserid();
				break;
			case 2:
				return $this->getTitle();
				break;
			case 3:
				return $this->getContent();
				break;
			case 4:
				return $this->getSpic();
				break;
			case 5:
				return $this->getRank();
				break;
			case 6:
				return $this->getHidden();
				break;
			case 7:
				return $this->getModeid();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = BlogPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getUserid(),
			$keys[2] => $this->getTitle(),
			$keys[3] => $this->getContent(),
			$keys[4] => $this->getSpic(),
			$keys[5] => $this->getRank(),
			$keys[6] => $this->getHidden(),
			$keys[7] => $this->getModeid(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = BlogPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setUserid($value);
				break;
			case 2:
				$this->setTitle($value);
				break;
			case 3:
				$this->setContent($value);
				break;
			case 4:
				$this->setSpic($value);
				break;
			case 5:
				$this->setRank($value);
				break;
			case 6:
				$this->setHidden($value);
				break;
			case 7:
				$this->setModeid($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = BlogPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setUserid($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setTitle($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setContent($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setSpic($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setRank($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setHidden($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setModeid($arr[$keys[7]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(BlogPeer::DATABASE_NAME);

		if ($this->isColumnModified(BlogPeer::ID)) $criteria->add(BlogPeer::ID, $this->id);
		if ($this->isColumnModified(BlogPeer::USERID)) $criteria->add(BlogPeer::USERID, $this->userid);
		if ($this->isColumnModified(BlogPeer::TITLE)) $criteria->add(BlogPeer::TITLE, $this->title);
		if ($this->isColumnModified(BlogPeer::CONTENT)) $criteria->add(BlogPeer::CONTENT, $this->content);
		if ($this->isColumnModified(BlogPeer::SPIC)) $criteria->add(BlogPeer::SPIC, $this->spic);
		if ($this->isColumnModified(BlogPeer::RANK)) $criteria->add(BlogPeer::RANK, $this->rank);
		if ($this->isColumnModified(BlogPeer::HIDDEN)) $criteria->add(BlogPeer::HIDDEN, $this->hidden);
		if ($this->isColumnModified(BlogPeer::MODEID)) $criteria->add(BlogPeer::MODEID, $this->modeid);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(BlogPeer::DATABASE_NAME);

		$criteria->add(BlogPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Blog (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setUserid($this->userid);

		$copyObj->setTitle($this->title);

		$copyObj->setContent($this->content);

		$copyObj->setSpic($this->spic);

		$copyObj->setRank($this->rank);

		$copyObj->setHidden($this->hidden);

		$copyObj->setModeid($this->modeid);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getBlogComments() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addBlogComment($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getPosts() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPost($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Blog Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     BlogPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new BlogPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Usr object.
	 *
	 * @param      Usr $v
	 * @return     Blog The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setUsr(Usr $v = null)
	{
		if ($v === null) {
			$this->setUserid(NULL);
		} else {
			$this->setUserid($v->getId());
		}

		$this->aUsr = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Usr object, it will not be re-added.
		if ($v !== null) {
			$v->addBlog($this);
		}

		return $this;
	}


	/**
	 * Get the associated Usr object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Usr The associated Usr object.
	 * @throws     PropelException
	 */
	public function getUsr(PropelPDO $con = null)
	{
		if ($this->aUsr === null && ($this->userid !== null)) {
			$this->aUsr = UsrPeer::retrieveByPk($this->userid);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aUsr->addBlogs($this);
			 */
		}
		return $this->aUsr;
	}

	/**
	 * Declares an association between this object and a SysPic object.
	 *
	 * @param      SysPic $v
	 * @return     Blog The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setSysPic(SysPic $v = null)
	{
		if ($v === null) {
			$this->setSpic(NULL);
		} else {
			$this->setSpic($v->getId());
		}

		$this->aSysPic = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the SysPic object, it will not be re-added.
		if ($v !== null) {
			$v->addBlog($this);
		}

		return $this;
	}


	/**
	 * Get the associated SysPic object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     SysPic The associated SysPic object.
	 * @throws     PropelException
	 */
	public function getSysPic(PropelPDO $con = null)
	{
		if ($this->aSysPic === null && ($this->spic !== null)) {
			$this->aSysPic = SysPicPeer::retrieveByPk($this->spic);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aSysPic->addBlogs($this);
			 */
		}
		return $this->aSysPic;
	}

	/**
	 * Declares an association between this object and a Mode object.
	 *
	 * @param      Mode $v
	 * @return     Blog The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setMode(Mode $v = null)
	{
		if ($v === null) {
			$this->setModeid(NULL);
		} else {
			$this->setModeid($v->getId());
		}

		$this->aMode = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Mode object, it will not be re-added.
		if ($v !== null) {
			$v->addBlog($this);
		}

		return $this;
	}


	/**
	 * Get the associated Mode object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Mode The associated Mode object.
	 * @throws     PropelException
	 */
	public function getMode(PropelPDO $con = null)
	{
		if ($this->aMode === null && ($this->modeid !== null)) {
			$this->aMode = ModePeer::retrieveByPk($this->modeid);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aMode->addBlogs($this);
			 */
		}
		return $this->aMode;
	}

	/**
	 * Clears out the collBlogComments collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addBlogComments()
	 */
	public function clearBlogComments()
	{
		$this->collBlogComments = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collBlogComments collection (array).
	 *
	 * By default this just sets the collBlogComments collection to an empty array (like clearcollBlogComments());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initBlogComments()
	{
		$this->collBlogComments = array();
	}

	/**
	 * Gets an array of BlogComment objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Blog has previously been saved, it will retrieve
	 * related BlogComments from storage. If this Blog is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array BlogComment[]
	 * @throws     PropelException
	 */
	public function getBlogComments($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BlogPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collBlogComments === null) {
			if ($this->isNew()) {
			   $this->collBlogComments = array();
			} else {

				$criteria->add(BlogCommentPeer::BLOGID, $this->id);

				BlogCommentPeer::addSelectColumns($criteria);
				$this->collBlogComments = BlogCommentPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(BlogCommentPeer::BLOGID, $this->id);

				BlogCommentPeer::addSelectColumns($criteria);
				if (!isset($this->lastBlogCommentCriteria) || !$this->lastBlogCommentCriteria->equals($criteria)) {
					$this->collBlogComments = BlogCommentPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastBlogCommentCriteria = $criteria;
		return $this->collBlogComments;
	}

	/**
	 * Returns the number of related BlogComment objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related BlogComment objects.
	 * @throws     PropelException
	 */
	public function countBlogComments(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BlogPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collBlogComments === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(BlogCommentPeer::BLOGID, $this->id);

				$count = BlogCommentPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(BlogCommentPeer::BLOGID, $this->id);

				if (!isset($this->lastBlogCommentCriteria) || !$this->lastBlogCommentCriteria->equals($criteria)) {
					$count = BlogCommentPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collBlogComments);
				}
			} else {
				$count = count($this->collBlogComments);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a BlogComment object to this object
	 * through the BlogComment foreign key attribute.
	 *
	 * @param      BlogComment $l BlogComment
	 * @return     void
	 * @throws     PropelException
	 */
	public function addBlogComment(BlogComment $l)
	{
		if ($this->collBlogComments === null) {
			$this->initBlogComments();
		}
		if (!in_array($l, $this->collBlogComments, true)) { // only add it if the **same** object is not already associated
			array_push($this->collBlogComments, $l);
			$l->setBlog($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Blog is new, it will return
	 * an empty collection; or if this Blog has previously
	 * been saved, it will retrieve related BlogComments from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Blog.
	 */
	public function getBlogCommentsJoinUsr($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BlogPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collBlogComments === null) {
			if ($this->isNew()) {
				$this->collBlogComments = array();
			} else {

				$criteria->add(BlogCommentPeer::BLOGID, $this->id);

				$this->collBlogComments = BlogCommentPeer::doSelectJoinUsr($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(BlogCommentPeer::BLOGID, $this->id);

			if (!isset($this->lastBlogCommentCriteria) || !$this->lastBlogCommentCriteria->equals($criteria)) {
				$this->collBlogComments = BlogCommentPeer::doSelectJoinUsr($criteria, $con, $join_behavior);
			}
		}
		$this->lastBlogCommentCriteria = $criteria;

		return $this->collBlogComments;
	}

	/**
	 * Clears out the collPosts collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPosts()
	 */
	public function clearPosts()
	{
		$this->collPosts = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPosts collection (array).
	 *
	 * By default this just sets the collPosts collection to an empty array (like clearcollPosts());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPosts()
	{
		$this->collPosts = array();
	}

	/**
	 * Gets an array of Post objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Blog has previously been saved, it will retrieve
	 * related Posts from storage. If this Blog is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Post[]
	 * @throws     PropelException
	 */
	public function getPosts($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BlogPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPosts === null) {
			if ($this->isNew()) {
			   $this->collPosts = array();
			} else {

				$criteria->add(PostPeer::BLOGID, $this->id);

				PostPeer::addSelectColumns($criteria);
				$this->collPosts = PostPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(PostPeer::BLOGID, $this->id);

				PostPeer::addSelectColumns($criteria);
				if (!isset($this->lastPostCriteria) || !$this->lastPostCriteria->equals($criteria)) {
					$this->collPosts = PostPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastPostCriteria = $criteria;
		return $this->collPosts;
	}

	/**
	 * Returns the number of related Post objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Post objects.
	 * @throws     PropelException
	 */
	public function countPosts(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BlogPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collPosts === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(PostPeer::BLOGID, $this->id);

				$count = PostPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(PostPeer::BLOGID, $this->id);

				if (!isset($this->lastPostCriteria) || !$this->lastPostCriteria->equals($criteria)) {
					$count = PostPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collPosts);
				}
			} else {
				$count = count($this->collPosts);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Post object to this object
	 * through the Post foreign key attribute.
	 *
	 * @param      Post $l Post
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPost(Post $l)
	{
		if ($this->collPosts === null) {
			$this->initPosts();
		}
		if (!in_array($l, $this->collPosts, true)) { // only add it if the **same** object is not already associated
			array_push($this->collPosts, $l);
			$l->setBlog($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Blog is new, it will return
	 * an empty collection; or if this Blog has previously
	 * been saved, it will retrieve related Posts from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Blog.
	 */
	public function getPostsJoinUsr($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BlogPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPosts === null) {
			if ($this->isNew()) {
				$this->collPosts = array();
			} else {

				$criteria->add(PostPeer::BLOGID, $this->id);

				$this->collPosts = PostPeer::doSelectJoinUsr($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PostPeer::BLOGID, $this->id);

			if (!isset($this->lastPostCriteria) || !$this->lastPostCriteria->equals($criteria)) {
				$this->collPosts = PostPeer::doSelectJoinUsr($criteria, $con, $join_behavior);
			}
		}
		$this->lastPostCriteria = $criteria;

		return $this->collPosts;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Blog is new, it will return
	 * an empty collection; or if this Blog has previously
	 * been saved, it will retrieve related Posts from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Blog.
	 */
	public function getPostsJoinMode($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(BlogPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPosts === null) {
			if ($this->isNew()) {
				$this->collPosts = array();
			} else {

				$criteria->add(PostPeer::BLOGID, $this->id);

				$this->collPosts = PostPeer::doSelectJoinMode($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PostPeer::BLOGID, $this->id);

			if (!isset($this->lastPostCriteria) || !$this->lastPostCriteria->equals($criteria)) {
				$this->collPosts = PostPeer::doSelectJoinMode($criteria, $con, $join_behavior);
			}
		}
		$this->lastPostCriteria = $criteria;

		return $this->collPosts;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collBlogComments) {
				foreach ((array) $this->collBlogComments as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collPosts) {
				foreach ((array) $this->collPosts as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collBlogComments = null;
		$this->collPosts = null;
			$this->aUsr = null;
			$this->aSysPic = null;
			$this->aMode = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseBlog:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseBlog::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseBlog
