dev:
  propel:
    param:
      classname: DebugPDO
 
test:
  propel:
    param:
      classname:  DebugPDO
 
all:
  propel:
    class: sfPropelDatabase
    param:
      dsn:        pgsql:dbname=taskana;host=127.0.0.1
      username:   postgres
      password:   p;[-p;[-
      encoding:   utf8
      persistent: true
      pooling:    true
      classname:  PropelPDO